// Date: 3/4/2015 2:33:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package io.github.javamatrix.randomtech.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelEnergyFez extends ModelBiped {
    // fields
    ModelRenderer tassle1;
    ModelRenderer FezStrand;
    ModelRenderer Fez;
    ModelRenderer tassle2;

    public ModelEnergyFez() {
        textureWidth = 64;
        textureHeight = 32;

        tassle1 = new ModelRenderer(this, 32, 10);
        tassle1.addBox(-0.5F, -14F, -0.5F, 1, 1, 1);
        tassle1.setRotationPoint(0F, 0F, 0F);
        tassle1.setTextureSize(64, 32);
        tassle1.mirror = true;
        setRotation(tassle1, 0F, 0F, 0F);
        FezStrand = new ModelRenderer(this, 32, 10);
        FezStrand.addBox(2F, -12F, 2.5F, 1, 3, 1);
        FezStrand.setRotationPoint(0F, 0F, 0F);
        FezStrand.setTextureSize(64, 32);
        FezStrand.mirror = true;
        setRotation(FezStrand, 0F, 0F, 0F);
        Fez = new ModelRenderer(this, 32, 0);
        Fez.addBox(-2.5F, -13F, -2.5F, 5, 5, 5);
        Fez.setRotationPoint(0F, 0F, 0F);
        Fez.setTextureSize(64, 32);
        Fez.mirror = true;
        setRotation(Fez, 0F, 0F, 0F);
        tassle2 = new ModelRenderer(this, 32, 10);
        tassle2.addBox(0.5F, -14F, 0.5F, 1, 1, 1);
        tassle2.setRotationPoint(0F, 0F, 0F);
        tassle2.setTextureSize(64, 32);
        tassle2.mirror = true;
        setRotation(tassle2, 0F, 0F, 0F);

        this.bipedHead.isHidden = true;
        this.bipedHeadwear.isHidden = true;
        this.bipedBody.isHidden = true;
        this.bipedCloak.isHidden = true;
        this.bipedEars.isHidden = true;
        this.bipedLeftArm.isHidden = true;
        this.bipedLeftLeg.isHidden = true;
        this.bipedRightArm.isHidden = true;
        this.bipedRightLeg.isHidden = true;

        this.bipedHead.showModel = false;
        this.bipedHeadwear.showModel = false;
        this.bipedBody.showModel = false;
        this.bipedCloak.showModel = false;
        this.bipedEars.showModel = false;
        this.bipedLeftArm.showModel = false;
        this.bipedLeftLeg.showModel = false;
        this.bipedRightArm.showModel = false;
        this.bipedRightLeg.showModel = false;
    }

    public void render(Entity entity, float f, float f1, float f2, float f3,
                       float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        GL11.glPushMatrix();
        GL11.glRotatef(f5, 0, 0, 1);
        GL11.glRotatef(f3, 0, 1, 0);
        GL11.glRotatef(f4, 1, 0, 0);
        tassle1.render(f5);
        FezStrand.render(f5);
        Fez.render(f5);
        tassle2.render(f5);
        GL11.glPopMatrix();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3,
                                  float f4, float f5, Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
        if (this.isSneak) {
            this.Fez.rotationPointY = 1.0F;
            this.FezStrand.rotationPointY = 1.0F;
            this.tassle1.rotationPointY = 1.0F;
            this.tassle2.rotationPointY = 1.0F;
        } else {
            this.Fez.rotationPointY = 0.0F;
            this.FezStrand.rotationPointY = 0.0F;
            this.tassle1.rotationPointY = 0.0F;
            this.tassle2.rotationPointY = 0.0F;

        }
    }

}
