// Date: 3/5/2015 6:43:59 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package io.github.javamatrix.randomtech.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBike extends ModelBase {
    private static ModelBike instance = null;
    // fields
    ModelRenderer BackWheel;
    ModelRenderer FrontWheel;
    ModelRenderer Shape1;
    ModelRenderer Shape2;

    public ModelBike() {
        textureWidth = 64;
        textureHeight = 32;

        BackWheel = new ModelRenderer(this, 0, 0);
        BackWheel.addBox(-1.5F, -1.5F, -0.5F, 3, 3, 1);
        BackWheel.setRotationPoint(5F, 0F, 0F);
        BackWheel.setTextureSize(64, 32);
        BackWheel.mirror = true;
        setRotation(BackWheel, 0F, 0F, 0.7853982F);
        FrontWheel = new ModelRenderer(this, 0, 0);
        FrontWheel.addBox(-1.5F, -1.5F, -0.5F, 3, 3, 1);
        FrontWheel.setRotationPoint(-5F, 0F, 0F);
        FrontWheel.setTextureSize(64, 32);
        FrontWheel.mirror = true;
        setRotation(FrontWheel, 0F, 0F, 0.7853982F);
        Shape1 = new ModelRenderer(this, 8, 0);
        Shape1.addBox(-5F, 0F, 0F, 10, 7, 0);
        Shape1.setRotationPoint(0F, -7F, 0F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 0, 7);
        Shape2.addBox(-0.5F, -0.5F, -2.5F, 1, 1, 5);
        Shape2.setRotationPoint(-3F, -7.5F, 0F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
    }

    public static ModelBike getInstance() {
        if (instance == null) {
            instance = new ModelBike();
        }
        return instance;
    }

    public void render(Entity entity, float f, float f1, float f2, float f3,
                       float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        BackWheel.render(f5);
        FrontWheel.render(f5);
        Shape1.render(f5);
        Shape2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3,
                                  float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        FrontWheel.rotateAngleZ += 5;
        BackWheel.rotateAngleZ += 5;
    }

}
