// Date: 2/23/2015 4:54:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package io.github.javamatrix.randomtech.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAutoHammer extends ModelBase {
    // fields
    ModelRenderer Base;
    ModelRenderer Arm;
    ModelRenderer Hammer;

    public ModelAutoHammer() {
        textureWidth = 128;
        textureHeight = 64;

        Base = new ModelRenderer(this, 0, 0);
        Base.addBox(-8F, 0F, -8F, 16, 7, 16);
        Base.setRotationPoint(0F, 8F, 0F);
        Base.setTextureSize(128, 64);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Arm = new ModelRenderer(this, 0, 24);
        Arm.addBox(-2F, 0F, -2F, 4, 7, 4);
        Arm.setRotationPoint(0F, 9F, 0F);
        Arm.setTextureSize(128, 64);
        Arm.mirror = true;
        setRotation(Arm, 0F, 0F, 0F);
        Hammer = new ModelRenderer(this, 64, 0);
        Hammer.addBox(-8F, 0F, -8F, 16, 2, 16);
        Hammer.setRotationPoint(0F, 15F, 0F);
        Hammer.setTextureSize(128, 64);
        Hammer.mirror = true;
        setRotation(Hammer, 0F, 0F, 0F);

    }

    public void render(Entity entity, float f, float f1, float f2, float f3,
                       float f4, float f5, int armOutness) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        int hammerOutness = armOutness;
        if (armOutness == 7) {
            armOutness = 6;
        }
        Arm.offsetY += armOutness / 16.0f;
        Hammer.offsetY += hammerOutness / 16.0f;
        Base.render(f5);
        Arm.render(f5);
        Hammer.render(f5);
        Arm.offsetY -= armOutness / 16.0f;
        Hammer.offsetY -= hammerOutness / 16.0f;
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3,
                                  float f4, float f5, Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    }

}
